### ISSUE TITLE
Spike: assess level of effort to use S3 for Fedora 6 OCFL root

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#103]
As part of ongoing questions noted in #100, how complex would it be store our OCFL root externally in S3?

For this ticket:

- [x] [Review Fedora 6 documentation for S3 usage](https://wiki.lyrasis.org/display/FEDORA6x/Amazon+S3)
- [x] Assess level of effort to store our Fedora 6 files in S3 through AWS@emory
- [x] Discuss with team if we should try this for our production data migration test in Sprint 5

**Comment by jcrompton42** [comment]
Level of effort for setting up s3 should be fairly low: maybe half a day and that's mostly AWS permissions. 

HOWEVER: we cannot use the migration tool and remote s3 storage at the same time.

**Comment by jcrompton42** [comment]
because the migration tool requires access to filesystems of both the source and destination fedora, and that's not something we can easily do with S3 through emory, I believe this work should wait until after prod migrations have been done.
