### ISSUE TITLE
Spike/question: how to get a simple count of objects and data streams migrated

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#104]
As part of ongoing questions logged in #100, is it possible to get a simple count of Fedora 3 objects and data streams migrated?

When we migrate a set of pids, we can easily confirm how many parent objects are created but identifying how many binary files were successfully attached to these works requires manual inspection.

Example from production sample data migration:
works: 85
datatreams/binary files attached to the works: 711
total Fedora 6 objects expected to be created: 796

**Comment by eporter23** [comment]
If I do a query like this in Fedora 6 search, it returns a list but does not provide counts. Maximum set is 100. http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/fcr:search?condition=rdf_type%3Dhttp%3A%2F%2Ffedora.info%2Fdefinitions%2Fv4%2Frepository%23Binary&offset=0&max_results=100

**Comment by abelemlih** [comment]
@eporter23 I found a report that should be useful for this use case: http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/fcr:stats/rdf-types

Additional details can be found in the documentation: https://wiki.lyrasis.org/display/FEDORA6x/Statistics

For instance, for binary files, the report lists them under `resource_type: "http://fedora.info/definitions/v4/repository#Binary"`, as shown in the JSON response below:

![Screenshot 2023-05-30 at 7.14.36 PM.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/129019f6-2a9e-450f-8230-328fbadffdb1)

**Comment by jcrompton42** [comment]
I wrote a simply script to evaluate csv reports from the migration validator tool. This will count the number of unique entries in column sourceResourceID
https://github.com/emory-libraries/middleware_utilities/blob/main/datastream_counts.py

**Comment by eporter23** [comment]
@abelemlih that is great! Sorry I missed your comment earlier. We now have two very helpful options!
