### ISSUE TITLE
Spike: assess pros and cons to using Archival Groups vs. Atomic Resources

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#105]
What are pros and cons to using Archival Groups vs. atomic resources in OCFL? What is the default for migrated objects?

For this ticket:

- [ ] Review documentation regarding OCFL options in Fedora 6
- [x] Review migrated data to see what the default output is
- [x] Consult with others using Archival Groups
- [ ] Assess impact on Valkyrie prototype if we change what we are currently using

https://wiki.lyrasis.org/display/FEDORA6x/Fedora+OCFL+Object+Structure
https://wiki.lyrasis.org/display/FEDORA6x/Auto-versioning

Work notes:
From reading Fedora docs and slack posts, the default output generated by the migration utility appears to be Archival Groups. Each work and its content files are contained in a single directory. The Archival Group appears to be created and then a new version is created each time a data stream is attached. A work with 8 data streams, for example, will have 8 versions right away.

When we transform the migrated objects' binaries into FileSets, we are then creating new OCFL objects (which I don't think are archival groups). 

On 5/23 we met with the Oxford Research Archive team who are also using Archival Groups. They prefer them due to their greater human readability. They also use "transactions" to reduce the number of versions that get created. 

Pros 

- Archival Groups are more human-friendly to review on disk
- Archival Groups may produce fewer sidecar files overall? (could be beneficial for fixity checking in the future)

Cons

- Adds complexity to trying to build Hyrax support, if we aim to replicate a Fedora 4-like container structure
- Any change to a constituent of an archival group will cause the entire object to be versioned (not recommended for collections, for example)
- Impact on Valkyrie prototype is unknown if we want to keep the original Archival Group structure intact after migration

**Comment by eporter23** [comment]
According to Fedora Migration slack channel, the migration utility does appear to create Archival Groups by default.  There is also an undocumented option to generate atomic resources instead. https://github.com/fcrepo-exts/migration-utils/blob/main/src/main/java/org/fcrepo/migration/PicocliMigrator.java#L95

**Comment by bwatson78** [comment]
@eporter23 From what I'm finding with the documentation you provided above, we can turn off auto-versioning and amend our persistent calls to specifically version certain procedures when we want that.

**Comment by bwatson78** [comment]
And as far as I can tell, any type of structure (archival or atomic) will have that versioning issue. Hyrax' structure resembles atomic structures more than archival, but I see no indications that Hyrax wouldn't inherently work with archival structure when I compare the two. 

@rotated8 Can you look at this [resource](https://wiki.lyrasis.org/display/FEDORA6x/Fedora+OCFL+Object+Structure) and let me know if I'm off base?

**Comment by bwatson78** [comment]
The main thing I'm taking away from the ArchivalObject structure is that the "bloat" associated with each attached resource is centralized rather than in associated containers.

**Comment by eporter23** [comment]
Another thing I’m wondering about is the amount of additional files (json, .nt etc) that get created, particularly in how that will impact fixity checking. Right now we can easily check a whole s3 bucket because all we store are content files. With OCFL and Fedora’s additional files our file counts will be considerably higher.

______________________________________________
Emily Porter
Digital Library Program Coordinator
Library & Information Technology Services
Emory University, Atlanta, GA 30322
________________________________
From: Brad Watson ***@***.***>
Sent: Tuesday, May 30, 2023 3:04:20 PM
To: emory-libraries/OpenEmory ***@***.***>
Cc: Porter, Emily K. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [emory-libraries/OpenEmory] Spike: assess pros and cons to using Archival Groups vs. Atomic Resources (Issue #105)


The main thing I'm taking away from the ArchivalObject structure is that the "bloat" associated with each attached resource is centralized rather than in associated containers.
