### ISSUE TITLE
Save as draft generates error in non-Article manual deposits 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#108]
When creating a new manual deposit, if a submitter clicks on Save Draft in the metadata edit form (#66), an application error results.

Steps to recreate:

1. Start a new record
2. Select a Type which is not an Article
3. Upload a file
4. Fill out portions of the metadata edit form for the selected content type
5. Click Save Draft instead of Submit
6. See error linked below
7. Go to Dashboard, see draft
8. Click Continue Editing
9. See that no metadata from the initial submission has been saved

See PDF of error output: [https://app.zenhub.com/files/8471248/282e1dd8-bc03-435c-8ed9-c836f237e4f2/download](https://app.zenhub.com/files/8471248/282e1dd8-bc03-435c-8ed9-c836f237e4f2/download)

**Comment by eporter23** [comment]
@alexBLR I retested this on 6/1 and can replicate the error if I select a type other than Article. Articles saved as drafts work fine.

**Comment by eporter23** [comment]
Also, if I create a non-article and Save Draft, the above error occurs, but I can see the draft in my documents. When I go to edit the non-article draft, none of the draft metadata has been saved.

**Comment by eporter23** [comment]
When testing with Tiffany's account, she created a new Report work and saved it as a draft, then went back to edit. When modifying the draft and clicking Submit, she got an "error communicating with the repository" message. 

![Screen Shot 2023-06-13 at 10.36.18 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/155e0908-42fe-4002-9d8d-19e4d300e7d3)

![Screen Shot 2023-06-13 at 10.37.00 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/df2318ec-a6c2-4470-8e29-89dddcd78bec)

**Comment by alexBLR** [comment]
@eporter23 please retest this. It should be working now.

**Comment by eporter23** [comment]
Re-tested with a non-admin user and Tiffany was able to submit her saved draft:![Screen Shot 2023-06-15 at 10.27.29 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/42ea7018-323d-4b66-8cf9-d3d50cd860dd)
