### ISSUE TITLE
Merge the "like for like' pre-existing and new Faculty deposits pids listed below in the description field.

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/OpenEmory#11]
Pre-Existing Deposit; New Deposit
emory:f7b6s; emory:rtm1d
emory:fkz0h;emory:rtqbz
emory:f7cs7; emory:rtqc3
emory:r7vwd; emory:rs0jj
emory:fm5q3; emory:rx429
emory:ff5hx; emory:rxds1
emory:fkvws; emory:rxngh
emory:fkx67; emory:rxnhn
emory:f7d9d; emory:rz225
emory:d8qmm; emory:s02t9
emory:fkxjm; emory:s02vf
emory:fkskb; emory:s02wk
emory:fm5sc; emory:s148c
emory:fkzw3; emory:s2gd1
emory:fkwx1; emory:s2gf5
emory:ff6j5; emory:s2h41
emory:f7hp7; emory:s30ch
emory:f59m6; emory:s30dn
emory:g28z9; emory:s30fs
emory:gjp9w; emory:s30gx
emory:f7vtt; emory:s32z2
emory:fjmp5; emory:rrx3g
emory:fhv6w; emory:rs051
emory:f3nn7; emory:rs0g8

**Comment by rosy1280** [comment]
for production only

**Comment by fpici** [comment]
@alexBLR Adding a couple more since the last batch:

Pre-Existing; New Deposit

emory:f4nw8; emory:s52nz
emory:f7nt6/; emory:s52mt

Thank you!

**Comment by fpici** [comment]
@alexBLR Looks great Zo. Many thanks. Ready for deploy :-)
