### ISSUE TITLE
Fedora6 Prototype: Wipe `file_set_ids` after all FileSets associated to Object are removed.

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/OpenEmory#110]
Expected Behavior: the ValkyrieObject's attribute of `file_set_ids` should be empty after the ValkyrieFileSet objects have been removed via button on the ValkyrieObject's show page.

**Comment by eporter23** [comment]
@bwatson78 or @abelemlih can you please confirm if this is already deployed?

**Comment by eporter23** [comment]
Looks good!
