### ISSUE TITLE
Create new Fedora6 Blacklight prototype

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/OpenEmory#116]
- [x] Create Github repository to house code (internal).
- [x] Generate Blacklight application with dependencies that mirror https://github.com/emory-libraries/fedora6-prototype.
- [x] Ensure connectivity to Solr instance by displaying `id` value of each object.
- [x] Create new web application instance
- [x] Ensure connective to Solr on first instance

**Comment by bwatson78** [comment]
Code is now live on https://github.com/emory-libraries/fedora6-blacklight-prototype . 

@jcrompton42 Please move this ticket to `Review` when the last two checkmarks are complete.

**Comment by jcrompton42** [comment]
@bwatson78 you can deploy to sandbox2-webapp, ip =10.65.19.88. The web folder is /opt/sandbox/ same as the first instance, and I can curl the solr address from it. 

You can reach a url for it at sandbox2.libraries.emory.edu (the cert error will go away once OIT issues me a new certificate, for now just trust it)
