### ISSUE TITLE
Spike: Assess gaps between prototype data and Hyrax/Fedora 4 data

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#117]
In Sprint 5 we added basic PCDM properties as well as FileSet properties. As a next step we need to assess what other containers and relationships may be needed for Hyrax compatibility.

**Comment by abelemlih** [comment]
Additional requirements include:
- Look into how ordered members are implemented in Hyrax
- Research how to implement a similar feature for the prototype
- Look into how access control is implemented in Hyrax

**Comment by eporter23** [comment]
@abelemlih I think Hyrax also requires all works to be part of an Admin set. We can figure out how to create one manually or once we get a Hyrax running, it should do that for us. Example from fedora 4 test object:
```
ns002: isPartOf
http://fedora-cor-test.library.emory.edu/fcrepo/rest/prod/ad/mi/n_/se/admin_set/default
```

**Comment by eporter23** [comment]
@abelemlih I also wonder if we need to populate at least Core Hyrax metadata noted here? https://samvera.github.io/metadata_application_profile.html

**Comment by abelemlih** [comment]
@eporter23 @bwatson78 I added some finding to the following [file](https://emory-my.sharepoint.com/:w:/r/personal/abeleml_emory_edu/Documents/Research/117-gaps_hyrax_4_fedora_prototype.docx?d=wceceaea138c940b58ccb8387fe7a75b0&csf=1&web=1&e=8Vs8ah) regarding some of the questions above. 

I am still researching ordered members and access control, and will add my findings to the same file. Let me know if you have any questions.

**Comment by eporter23** [comment]
@abelemlih thanks for these notes! it is interesting about Admin sets not being required. When we ingest items to Curate, for example, both bulk import and UI work creation enforce a work being added to an admin set. In both cases they are always deposited as members of the Default Admin Set (even if no explicit selection is made).

**Comment by abelemlih** [comment]
@eporter23 @bwatson78 I added my last comment concerning ordered members to the document above. Please let me know if there are any additional questions/topics I should look into.

**Comment by abelemlih** [comment]
Both Emily and Brad reviewed my findings and recommended I close this ticket.
