### ISSUE TITLE
Permanent URL link/href errors 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#118]
The formatting of the PID url contains extra characters and the href is not formatted correctly:

![Screen Shot 2023-06-01 at 12.23.35 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/de045a0e-292b-48fd-a152-2452ce5b73f8)

**Comment by alexBLR** [comment]
Newly deposited publications won't have that problem.

**Comment by alexBLR** [comment]
![Screen Shot 2023-06-13 at 8.51.50 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/373cca2a-2619-4536-b891-250667b57f81)

**Comment by eporter23** [comment]
Confirmed that new deposits show the URL correctly. Thanks!
