### ISSUE TITLE
Test QA with new Database

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/OpenEmory#126]
We can do preliminary testing, but SCO needs to do the bulk.

Testing steps identified by Scrum Team and SCO for the most frequently used areas of the Django Admin interface:
statistics, profiles, licenses, harvest record counts; anything with counts in the django admin area. Make sure we can read data and also update data (edit some flat pages, licenses, a profile etc.) 

Flat pages
- [x] Expected Flat pages are listed
- [x] Edit a flat page and save changes
Users
- [x] Expected list users matches
- [x] Edit a profile and save changes
Licenses
- [x] Expected licenses are listed
- [x] Edit a license and save changes
Harvest records
- [x] SCO to test and confirm

**Comment by eporter23** [comment]
I've contacted Kylie and requested she do additional testing by 7/19 at latest.
