### ISSUE TITLE
OpenEmory download stats for FY17 Sept 1, 2016-Aug 31, 2017

### ISSUE THREAD

**Issue by fpici** [emory-libraries/OpenEmory#13]
As an OpenEmory Admin I want to see the download stats for FY17 (Sept 1, 2016-Aug 31, 2017) so I can provide these stats to AIG.

**Comment by fpici** [comment]
@alexBLR Hi Zo. Jen just let me know that AIG has a deadline of 2.23.2018 for these stats :-) Please let me know if this is at all possible by that date?

Sorry ... :-(

**Comment by alexBLR** [comment]
done
