### ISSUE TITLE
Add Desired Fields to Fedora6 Blacklight Prototype

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/OpenEmory#133]
@eporter23 will add desired fields later.

See [Basic display specs for Blacklight](https://docs.google.com/document/d/1WP3IGFbAkZWybZbe6MTVJusKIv8uZauD_yLfk7CYlKc/edit?usp=sharing), including:

- Facets
- Search results fields
- Record detail fields and links

**Comment by eporter23** [comment]
@bwatson78 I wrote up some basic specs for display and added the link to the ticket description above.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/fedora6-blacklight-prototype/pull/1

That addresses the majority of the requested fields. Will be tackling the Download links after working on capistrano integration.

**Comment by eporter23** [comment]
@bwatson78 PubMed links are looking good, but the Content File links error out. Example: https://sandbox2.libraries.emory.edu/catalog/emory:pmr1b links to  https://sandbox2.libraries.emory.edu/emory:pmr1b/content

**Comment by bwatson78** [comment]
That's my bad. I forgot to add in a Rails ENV.

**Comment by bwatson78** [comment]
Fixed!

**Comment by eporter23** [comment]
Looks great!
