### ISSUE TITLE
Test Prod with new Database

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/OpenEmory#134]
We can do preliminary testing, but SCO needs to do the bulk.

- [x] Add Emily as an admin user in production

Testing steps identified by Scrum Team and SCO for the most frequently used areas of the Django Admin interface:
statistics, profiles, licenses, harvest record counts; anything with counts in the django admin area. Make sure we can read data and also update data (edit some flat pages, licenses, a profile etc.)

Flat pages
- [x] Expected Flat pages are listed
- [x] Edit a flat page and save changes
- [x] Create a new flat page and save it

Users
- [x] Admin users can still access Django admin area of site
- [x] Expected list users matches
- [x] Edit a profile and save changes

Licenses
- [x] Expected licenses are listed
- [x] Edit a license and save changes

Harvest records
- [x] SCO to test and confirm

**Comment by eporter23** [comment]
Kylie noted that no data exists after 7/19 for the Harvest records section despite activity between then and the 25th. Is this due to the timing of the snapshot vs the delay in the new database getting connected?

**Comment by eporter23** [comment]
Zo will look into whether the cron job is running and hopefully this will catch us up.

**Comment by eporter23** [comment]
Discussed in sprint planning, if we need the data refreshed for those missing days, we can try to run the cron job.

**Comment by eporter23** [comment]
I think it is safe to close this now. I will coordinate any new ticket creation with SCO if they see issues with the Harvest Records data not populating.
