### ISSUE TITLE
Remove selected browse pages

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#136]
The following pages were requested by SCO to be removed from the OpenEmory Browse menu, because either they are not fully functioning or they contain out of date information:
 
- [x] Disable/delete the Faculty by Department browse view: https://open.library.emory.edu/profiles/departments/
- [x] Disable/delete the Works by Department browse view: https://open.library.emory.edu/publications/departments/

**Comment by alexBLR** [comment]
![Screen Shot 2023-06-13 at 8.44.15 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/9ef1e1e0-d5de-4196-a234-b7b5e152e64c)
