### ISSUE TITLE
Editing/creating flat pages in testopen

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#137]
When using the Django admin tools to create flat pages in the test environment, the pages appear to be created, but cannot be accessed. I'm not sure if this is a bug, or if I'm doing something incorrectly.

Example: 

![Screenshot 2023-06-07 at 3.32.35 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/26d3df0f-dd0d-431a-bb62-24e8f0d22f5e)![Screenshot 2023-06-07 at 3.32.59 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9a84d623-2ae1-4193-9a0b-be955519788b)

Additionally, if I try to use the View on Site option to view an existing flat page that I did not create, I get a page does not exist error.
![Screenshot 2023-06-07 at 3.30.28 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/cd362184-0c81-4874-9a5c-f49d7321fcb6)

**Comment by alexBLR** [comment]
Please go directly to the page: https://testopen.library.emory.edu/about/self-deposit/

When creating a new page indicate open.library.emory.edu and not testopen.library.emory.edu  in Sites

**Comment by eporter23** [comment]
When the content page(s) are ready I will write up another ticket to have these added to the site's navigation.
