### ISSUE TITLE
Blacklight prototype, v.2 items

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#139]
Following work to get an initial prototype in place, additional refinements have been added to the Blacklight basic specs document.

- [x] Remove FileSets from search results
- [x] Enable all fields to be searchable
- [x] Add a basic date/year facet (requires additional MODS extraction)
- [x] Add an entertaining image to replace the default homepage text block

See the [spec document](https://docs.google.com/document/d/1WP3IGFbAkZWybZbe6MTVJusKIv8uZauD_yLfk7CYlKc/edit#) for more details.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/fedora6-blacklight-prototype/pull/6

**Comment by eporter23** [comment]
All looks good except for our unfortunate indexing snafu!
