### ISSUE TITLE
Requesting OpenEmory Admin Access for two New SCO Student Workers:

### ISSUE THREAD

**Issue by fpici** [emory-libraries/OpenEmory#14]
1) Tyra Satchell; Net ID: TSATCH2 (tyra.satchell@emory.edu)

2) Jason Adam Hardman; Net ID: JAHARDM (jason.hardman@emory.edu)

Zo, both students will need Admin Staff access with the ability to edit records in OpenEmory.  

Thank you!

**Comment by alexBLR** [comment]
Done
