### ISSUE TITLE
MODS date extraction results in SOLR errors

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#143]
With our recent MODS extraction mapped to date_issued, the date values in OpenEmory are typically in the format of YYYY, YYYY-MM, or YYYY-MM-DD. We notice that the dates are being converted to a date/timestamp format instead, which results in errors for the Valkyrie SOLR fields. This is causing our re-indexing to fail.

example:
MODS date: "2005-05-31"

SOLR value gets converted to: "2005-05-31T00:00:00Z"

Possible options:

- Try to fix the behavior locally
- Revert the MODS date extraction work
- Document the behavior to investigate later (or share with Valkyrie team)

**Comment by bwatson78** [comment]
Below is the setting in `solrconfig.xml` that lists the allowed formats for dates:

```
  <updateProcessor class="solr.ParseDateFieldUpdateProcessorFactory" name="parse-date">
    <arr name="format">
      <str>yyyy-MM-dd['T'[HH:mm[:ss[.SSS]][z</str>
      <str>yyyy-MM-dd['T'[HH:mm[:ss[,SSS]][z</str>
      <str>yyyy-MM-dd HH:mm[:ss[.SSS]][z</str>
      <str>yyyy-MM-dd HH:mm[:ss[,SSS]][z</str>
      <str>[EEE, ]dd MMM yyyy HH:mm[:ss] z</str>
      <str>EEEE, dd-MMM-yy HH:mm:ss z</str>
      <str>EEE MMM ppd HH:mm:ss [z ]yyyy</str>
    </arr>
  </updateProcessor>
```
We could update this to our liking and rebuild successfully. This wouldn't jeopardize our matching to Hyrax--we would just want to match this to what our Hyrax expects.

**Comment by eporter23** [comment]
I'd probably not want to try to rebuild the above to match our date logic. Not sure where all of this is in our Curate/Lux code, but here is a summary of the date parsing logic we support: https://docs.google.com/spreadsheets/d/1tm7RDYWVcAWEZuA-lB3cbxxGI4qjn8uCn71X2EJPB50/edit#gid=557677526

**Comment by bwatson78** [comment]
This led to the ticket https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/145 to investigate how the differences between Curate's and this Solr's `solrconfig.xml` may provide a solution to this.
