### ISSUE TITLE
Assess SOLR fields that may need to be stored without Valkyrie's prefixing [placeholder]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#147]
In prior tests of how Valkyrie persists values to SOLR, in some cases a prefix is added to text fields. We don't yet know how these will be interpreted by the Hyrax interface, but we do suspect they may be problematic in a Blacklight display and for certain types of direct queries in SOLR.

Examples:
uri-
id-
integer-

**Comment by abelemlih** [comment]
For reference, the prefix added to fields types like `uri` and `integer` are required for the Valkyrie to convert between a resource and a Solr hash correctly. This is documented in this [issue](https://github.com/samvera/valkyrie/issues/616).
