### ISSUE TITLE
Google Analytics 4 updates for production

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#149]
While reviewing analytics accounts for the Google Analytics 4 upgrade, I found that the production site does not report any analytics tracking code embedded. The test environment, however, is reporting data and seems to use the code intended for production.

An updated code snippet has been generated that we can add to production: [https://app.zenhub.com/files/8471248/0d095d51-efab-458a-938d-08e5e3cab468/download](https://app.zenhub.com/files/8471248/0d095d51-efab-458a-938d-08e5e3cab468/download).

**Comment by eporter23** [comment]
@alexBLR can you please re-enable analytics in the test environment so I can check it? After that I will close this ticket and we can re-test in production later.

**Comment by alexBLR** [comment]
@eporter23 Done.
