### ISSUE TITLE
Reports for Annual Review

### ISSUE THREAD

**Issue by amiles4** [emory-libraries/OpenEmory#15]
Reports needed by May 23:
I need the following reports run in OpenEmory from May 2017-May 2018:

- Total Works
- Downloads
- Users
- Total faculty profiles

I need the following report from 2015-2018:

- Works added per year

**Comment by alexBLR** [comment]
**May 2017 - May 2018**
Total New Works: 3057
Total Downloads: 961,621
New Users: 91
New Faculty Users: 49

Works added 2015-2016:  923
Works added 2016-2017:  1771
Works added 2017-2018:  3260
Works added 2018-now: 1177
