### ISSUE TITLE
Blacklight Prototype - Basic Display Specs v3

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/OpenEmory#156]
See this document for reference: https://docs.google.com/document/d/1WP3IGFbAkZWybZbe6MTVJusKIv8uZauD_yLfk7CYlKc/edit#heading=h.2229iz7u0xl8

- [x] Omit Withdrawn items from search results (Solr field `state_tesim` does not equal "Inactive.")

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/fedora6-blacklight-prototype/pull/9

**Comment by eporter23** [comment]
Looks good @bwatson78 ! I cannot see withdrawn records in Blacklight, and I do see them in SOLR which is what we want. Also, the MODS dates are looking good for `date_issued`.
