### ISSUE TITLE
New SCO Student Admin Privileges in OpenEmory

### ISSUE THREAD

**Issue by fpici** [emory-libraries/OpenEmory#16]
Requesting OpenEmory Admin Access for two New SCO Student Staffer: 1). NetID: AHABDU2. Name:  Amna Abdulsalam -- (amna.hassana.abdulsalam@emory.edu).
2) NETID: JPINON. Name: Jessica Pinon -- (jessica.c.pinon@emory.edu).
Alex.  They are confirmed to start tomorrow but we will not have them working in OpenEmory until Monday Sept. 10th. Many thanks for your quick action :-)

**Comment by fpici** [comment]
Howdy Zo. Any updates or estimates on when you can get to this?  Many thanks!

**Comment by alexBLR** [comment]
done
