### ISSUE TITLE
Faculty depositor does not see links to Profile or Dashboard when logging in

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#163]
During QA testing with the SCO team, John Morgenstern (who does not have admin access to OpenEmory) logged in to test a deposit, but he does not see options to view his profile or dashboard. This user has never logged into testopen before.

![Screen Shot 2023-06-29 at 1.17.57 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/658e2fe3-f28d-494e-8c68-56c64c6f599a)

**Comment by alexBLR** [comment]
This is related to the issue with ESD data. I just fixed the ESD faculty indexer that should run nightly. It should solve a lot of problems for us. Related to suggested authors as well as links to other objects.

The command is running right now and trying to reindex 76k faculty members.

**Comment by eporter23** [comment]
Adding to Zo's comment above, we are simplifying the logic so that when a user logs in, they are treated as either an admin or not. If they are an OpenEmory admin, they'll see options in the header for the Admin dashboard. Otherwise, they'll see links to Profile, Documents, and Dashboard. This change will help ensure users who aren't synced up in ESD in OpenEmory can still login and manually deposit. This also allows us to accept submissions from grad students, researchers etc who may not be qualified as "faculty" in ESD.

**Comment by eporter23** [comment]
Tested this with Brad (who has never logged into testopen before) and he sees the dashboard and profile links. I will also ask Jenny Townes to retest.![Screenshot 2023-07-18 at 9.00.44 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/80536dcc-064f-4b8a-82f7-c4df305df027)

**Comment by eporter23** [comment]
Tested again with Jenny and she sees the appropriate options now. Thanks @alexBLR !
