### ISSUE TITLE
Permanent URL/pid links try to resolve to open.library and return 404 message

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#164]
Apologies for missing this earlier, but when testing with SCO we realized that the PID links, while properly formatted, are returning 404 errors because they are trying to resolve to open.library instead of testopen.library.

Example: http://pidqas.library.emory.edu/ark:/25593/rr255

**Comment by alexBLR** [comment]
From now on, when ingested in Test OE it should point to testopen.

**Comment by eporter23** [comment]
@alexBLR just uploaded a new work in testopen, but the PID url still tries to resolve to open.library: 
https://testopen.library.emory.edu/publications/emory:rr28k/
http://pidqas.library.emory.edu/ark:/25593/rr28k

**Comment by eporter23** [comment]
Discussed with @alexBLR that this is low priority to fix, given that it works in production. So, if there is an easy fix, let's go for it, otherwise don't spend much time on it.

**Comment by eporter23** [comment]
This is specific to the test environment only and we aren't pursuing resolving this.
