### ISSUE TITLE
Embargo durations add 6 months to selected end date

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#166]
When testing all the embargo options a work, I noticed that while the general embargo functionality works as expected (non-admins cannot download the content, and see an embargo message), the end date calculated seems to be inconsistent with the selected option by adding 6 months to the period:

When testing all the embargo options on a work on 6/30/23
unknown - works as expected
6 month - works but sets 1 year? Sets as 7/1/24 (expected 12/31/23 or 1/1/24)
12 month - works, but sets 18 months? Sets as 1/1/25 
18 months - works, but sets to 7/1/25 
24 months - sets to 1/1/26 36 months - sets to 1/1/27 
48 months - sets to 1/128 
Indefinite - works as expected

**Comment by alexBLR** [comment]
@eporter23 The embargo is calculated relative to the publication date set in :attr:`publication_date` if set.  If the date is year or year-month only, embargo will be calculated from the first day of the next year or month (e.g., for a publication date of 2012, the embargo will be calculated from 2013-01-01.)

**Comment by alexBLR** [comment]
@eporter23 The embargo is calculated relative to the publication date set in :attr:`publication_date` if set.  If the date is year or year-month only, embargo will be calculated from the first day of the next year or month (e.g., for a publication date of 2012, the embargo will be calculated from 2013-01-01.)

**Comment by alexBLR** [comment]
@eporter23 could you provide some objects, so I can test the embargo?

**Comment by eporter23** [comment]
@alexBLR thanks so much for clarifying! I was testing this on fake objects with dates only set to year only (2023) for the most part. Here is the one that I tested all the different embargoes: https://testopen.library.emory.edu/publications/emory:rr1vt/

**Comment by eporter23** [comment]
Also, here is another one that Kylie added. 
https://testopen.library.emory.edu/publications/emory:rr269/

**Comment by eporter23** [comment]
@alexBLR thanks for your helpful notes. I will close this because the above example shows that a more precise date entry calculates as expected.
