### ISSUE TITLE
Embargoed works should not be Public in Hyrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#168]
After initial development to be able to view migrated works in Hyrax, we should also look into making sure embargoed works do not have Public visibility.

Options:

1. Set embargoed works to be Private for now. This can be determined by looking at our `access_restriction_notes` field defined in Valkyrie, which will contain the word "embargoed"
2. Research what would be needed to set a Hyrax embargo (this may be better as its own spike ticket)

The second option would require us to have an Admin set created that allows for open-ended embargoes. I can provide more information about that if we want to investigate.  

Examples of embargoed works:
emory:w3jb4
emory:w287t
emory:w3xk7
emory:mr9zx

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/fedora6-prototype/pull/29

**Comment by eporter23** [comment]
Looks good @bwatson78 ! The works are now private, and I can't see them when not logged in (as expected).
