### ISSUE TITLE
SCO needs OpenEmory DOWNLOAD stats for fiscal year Sept 1, 2017-Aug 31, 2018.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/OpenEmory#17]
Please use date range 9/1/2017 through 8/31/2018 when running reports.

Jen Doty needs this by September 20th.

**Comment by alexBLR** [comment]
date range 9/1/2017 through 8/31/2018

{'num_views__sum': 254311}
{'num_views__sum': 207036}
{'num_views__sum': 298306}
{'num_views__sum': 287804}

total views = 1047457

{'num_downloads__sum': 209096}
{'num_downloads__sum': 219292}
{'num_downloads__sum': 291036}
{'num_downloads__sum': 220493}

total downloads = 939917
