### ISSUE TITLE
Create production launch plan for manual deposit

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#174]
The goal of this ticket is to identify tasks needed for going live with manual deposit, and immediate post-launch activities.

- [x] Determine if we combine the MySQL migration with production OpenEmory deployment (No, we will do them separately)
Confirm downtime window
Determine schedule for launch
Deploy OpenEmory to production
Re-index ESD for author lookup
Enable Google Analytics in production
Recreate flat page content changes
Add new Deposit Instructions page to site navigation
Conduct functional testing in production with SCO
Identify users who can deposit real material in production
Work with SCO to identify additional depositors for soft-launch testing
External communications

**Comment by jcrompton42** [comment]
I would prefer we do the mysql migration separately.

**Comment by eporter23** [comment]
@jcrompton42 I agree.
