### ISSUE TITLE
Adjust/remove footer elements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#177]
While doing ongoing functional testing, I noticed a few issues with elements in the footer that would be good to resolve if possible prior to our production launch. See the highlighted items on the screenshot below.

![OE Footer.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8628019f-2cda-456f-81f2-8485fe1562b5)

**Privacy Policy**
Update the link URL to go to https://libraries.emory.edu/about/policies/emory-libraries-privacy-policy

**Recent and Popular Items button**
This link, when clicked in production, returns no data. In test, it returns an error.
Recommendation:

- Remove this button

**Faculty Profiles Statistic**
Due to recent reindexing efforts in test, this number now shows close to 80,000 profiles, but we don't actually have that many submitters, so the data looks misleading.

Recommendation: 

- Remove this element
- OR, adjust it so that it only reflects the count of authors with published works

Production footer shows ~7,000 author profiles:
![Screenshot 2023-07-13 at 2.15.46 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9b0b6ae4-ecb5-44c2-befb-64863748f7cf)

**Comment by eporter23** [comment]
Due to competing projects, we are moving this into the Backlog for now.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/OpenEmory/pull/211

**Comment by eporter23** [comment]
We will deploy to testopen first, then production

**Comment by eporter23** [comment]
@bwatson78 looks great in testopen!
