### ISSUE TITLE
Backup and re-set Fedora 6 data

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#183]
Since we are stopping our work with the Valkyrie prototyping, we want to clear out the previously migrated data stored in Fedora 6 so we can begin prototyping another method to create data.

- [x] Create a tar file of our current Fedora 6 OCFL root
- [ ] Delete the files in the OCFL root
- [x] Reset the Fedora index so that it has no data

**Comment by jcrompton42** [comment]
backed up ocfl root can be found here https://emory-my.sharepoint.com/:u:/g/personal/jcrompt_emory_edu/EaX1mv89R1NKgyZNpFcJ0BgBzMMYpk8Rhx_7j_T2EGN9Zg?e=DaNV2g

**Comment by jcrompton42** [comment]
fedora has been backed up, cleared, and reindexed.
