### ISSUE TITLE
Re-set existing Hyrax 4 prototype application to defaults for ActiveFedora testing

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#184]
Since we have halted work on our Valkyrie prototype, we want to re-set our vanilla Hyrax application in order to test the ability to persist new objects through Hyrax to Fedora 6.

- [x] Look at forking/branching the Valkyrie work to keep it; or use a different name for ActiveFedora releases (same repo or a new one?)
- [x] Remove any overrides
- [x] Perform standard generic Hyrax setup tasks (ensure an Admin Set is created, admin user, etc.)
- [x] Clear out prior Valkyrie data from our SOLR instance

NOTE: we should make sure our Fedora instance and SOLR instances are re-set prior to any deployments - see #183.

**Comment by bwatson78** [comment]
For now, I'm resetting the app in the `hyrax_app_no_overrides` branch.

**Comment by bwatson78** [comment]
Solr wiped.

**Comment by bwatson78** [comment]
Branch deployed successfully, Fedora6, Postgres, and Solr working as expected. Default Admin Set and generic Collection Type of "OpenEmory Collection" created. I have caught up with Ayoub as far as code he's created from Dassie.
