### ISSUE TITLE
Export OCFL objects from ActiveFedora testing

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#189]
Before we decommission our Fedora 6 test environment, we should do a final export of the OCFL root so that we can compare the OCFL output generated directly by Hyrax vs by the migration utilities.

**Comment by eporter23** [comment]
@jcrompton42 please check in with @bwatson78 and I before you pick up this ticket, because we may want to wipe Fedora again after we do an OCFL backup.

**Comment by jcrompton42** [comment]
@bwatson78 says no wiping needed, so I backed up. 

Backup available https://emory-my.sharepoint.com/:u:/g/personal/jcrompt_emory_edu/ESezfq4RLdlGjEwFh7NOW5cBLqenpBZQHYpjlaVepHBx5g?e=Att8zT
