### ISSUE TITLE
Requesting OpenEmory Admin Access for New Head of SCO Jody Bailey

### ISSUE THREAD

**Issue by fpici** [emory-libraries/OpenEmory#19]
Requesting OpenEmory Admin Access for New Head of SCO: 
NetID: JEBAIL5. Name: Bailey, Jody Elizabeth-- (jody.bailey@emory.edu).

Many thanks in advance!

**Comment by alexBLR** [comment]
done.

**Comment by fpici** [comment]
Dear Zo.

Works just fine. I and Jody thank you!!!

Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html
