### ISSUE TITLE
Adjust/remove header elements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#190]
Because the OpenEmory site was originally launched in 2013, there are 2 header elements that are out of date and need revision or removal.

- [x] Remove Schools | Libraries | Resources menu: this is very out of date and also drops down over the login menu when a user is trying to type
- [x] Revise the "MARBL" link to say "Rose"
- [x] Update the Law Library link to point to https://library.law.emory.edu/

![Screen Shot 2023-07-20 at 9.41.49 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/af1db13e-ec62-4fbb-9b98-dce4148418af)

**Comment by eporter23** [comment]
Due to competing projects, we are moving this into the Backlog for now.

**Comment by eporter23** [comment]
@bwatson78 , @rotated8 and I discussed this as work we'd like to complete before the project closes on 8/31. We're hoping you may be able to tackle this to get it off Zo's plate. We'll discuss more during sprint planning.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/OpenEmory/pull/212

**Comment by eporter23** [comment]
We will deploy to testopen first, then production

**Comment by eporter23** [comment]
@bwatson78 looks good, but I am still seeing the Schools | Libraries | Resources menu in testopen.library: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGtNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d64e60d43d7304651b9376a045bc3c39d673432/Screen%20Shot%202023-08-16%20at%2011.19.58%20AM.png)

**Comment by bwatson78** [comment]
I just checked both testopen and prod, and I see that that menu is gone in testopen, and that none of the intended changes are live on prod yet.

**Comment by eporter23** [comment]
@bwatson78 just cleared cache etc in Chrome and I see the change now. Unfortunately the lower menu position has shifted upwards, are you seeing this too? (the Browse/About/etc menus should be flush with the bottom of the darker blue header element.) I'll look at it in more detail but I guess my visibility quick fix isn't quite enough.  
<img width="424" alt="Screen Shot 2023-08-16 at 12 50 28 PM" src="https://github.com/emory-libraries/OpenEmory/assets/13855987/276e8264-64eb-43cf-8827-35feff54b279">

**Comment by bwatson78** [comment]
I'll work on that!

**Comment by eporter23** [comment]
Looks great, thanks for the additional work on this.
