### ISSUE TITLE
Incorporate most recent ActiveFedora changes into Hyrax/Fedora 6 prototype

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#195]
See samvera/active_fedora#1497

**Comment by eporter23** [comment]
Discussed needing Redis as part of this.

**Comment by abelemlih** [comment]
@eporter23 I deployed the ActiveFedora changes to the instance, and creating a work/uploading files works. Refer to: https://sandbox3.libraries.emory.edu/concern/generic_works/m613mx563?locale=en
