### ISSUE TITLE
BUG: Files Do Not Associate and FileSets Do Not Create

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/OpenEmory#196]
Previous to @abelemlih's work [here](https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/191), Files attached to a work during UI `New Generic Work` processing did not persist, while also producing an error. By incorporating [Chiris Colvard's ActiveFedora work](https://github.com/samvera/active_fedora/pull/1497), he has eliminated the errors, but the Files requested to attach still do not persist. 

Goal: override current Hyrax behavior to allow Files to successfully persist in Fedora6 instance.

**Comment by abelemlih** [comment]
@eporter23 I deployed the ActiveFedora changes to the instance, and creating a work/uploading files works. Refer to: https://sandbox3.libraries.emory.edu/concern/generic_works/m613mx563?locale=en
