### ISSUE TITLE
Test using Bulkrax to create works (ActiveFedora) in Fedora 6

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#198]
Configure a basic Bulkrax CSV importer that supports:

- [x] Hyrax basic/core metadata profile
- [x] Ability to attach at least the primary content file for each work
- [ ] Bonus: Ability to attach more than one file(set) for each work

We will try to use as many default options as possible to reduce complexity for prototyping.

We may also want to look at #199 to ensure that if we run an import, we can generate thumbnails.

**Comment by eporter23** [comment]
Notes from sprint review: this may be a Hyrax 4 bug.

**Comment by bwatson78** [comment]
PR ready for review: https://github.com/emory-libraries/fedora6-hyrax-prototype/pull/15

**Comment by bwatson78** [comment]
The above PR has been merged and deployed, and these are some observations so far:
- The ingests for GenericWorks process without error. 
- Issues arise with FileSets, though. I have confirmation that they fully form, but problems arise during association. Below, we have the failing traceback from the server:
```E, [2023-07-31T16:46:08.688993 #940521] ERROR -- : [ActiveJob] [Bulkrax::CreateRela
tionshipsJob] [e83a3ede-1c49-4c9f-aee2-e9a03103fcce] Error performing Bulkrax::Crea
teRelationshipsJob (Job ID: e83a3ede-1c49-4c9f-aee2-e9a03103fcce) from Async(import
) in 128.54ms: ArgumentError (wrong number of arguments (given 1, expected 0; requi
red keywords: parent_identifier, importer_run_id)):
/opt/sandbox/shared/bundle/ruby/3.1.0/gems/bulkrax-5.2.1/app/jobs/bulkrax/create_re
lationships_job.rb:131:in `reschedule'
/opt/sandbox/shared/bundle/ruby/3.1.0/gems/bulkrax-5.2.1/app/jobs/bulkrax/create_re
lationships_job.rb:85:in `perform'
/opt/sandbox/shared/bundle/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/executi
on.rb:48:in `block in perform_now'
/opt/sandbox/shared/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support
/callbacks.rb:117:in `block in run_callbacks'
/opt/sandbox/shared/bundle/ruby/3.1.0/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_loc
ale'
```
The error that the importer picked up is more telling:
```
Errored at: 2023-07-31 16:49:54 UTC

Error: Ldp::NotFound - Error: Path /prod/34/e8/fc/62/34e8fc62-0194-40e9-b2a7-afc125f0c34c not found

Error Trace:

/opt/sandbox/shared/bundle/ruby/3.1.0/gems/ldp-1.2.0/lib/ldp/client/methods.rb:119:in `block in check_for_errors'

<internal:kernel>:90:in `tap'

/opt/sandbox/shared/bundle/ruby/3.1.0/gems/ldp-1.2.0/lib/ldp/client/methods.rb:117:in `check_for_errors'

/opt/sandbox/shared/bundle/ruby/3.1.0/gems/ldp-1.2.0/lib/ldp/client/methods.rb:82:in `block in post'

/opt/sandbox/shared/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:205:in `instrument'

/opt/sandbox/shared/bundle/ruby/3.1.0/gems/ldp-1.2.0/lib/ldp.rb:43:in `instrument'

/opt/sandbox/shared/bundle/ruby/3.1.0/gems/ldp-1.2.0/lib/ldp/client/methods.rb:74:in `post'

/opt/sandbox/shared/bundle/ruby/3.1.0/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/caching_connection.rb:19:in `post'

/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/delegate.rb:87:in `method_missing'
```
I looked that object up in Fedora6 and found it did exist, but it was not stored in a pairtree structure--it was stored in root. I'm reaching out now in Samvera's Slack to see if this is the new normal for just `Hydra::AccessControl` objects, but not all others.

**Comment by bwatson78** [comment]
Proof of `Hydra::AccessControl`: http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/prod/34e8fc62-0194-40e9-b2a7-afc125f0c34c

![Screenshot 2023-07-31 at 3.21.54 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/46c984ed-87ba-4052-bab7-e5cc1d4b3183)

**Comment by bwatson78** [comment]
Further Findings:
The FileSets created by the Importer are fully-formed and persisted, but two associated processes do not happen, and they both exist within the same Bulkrax Job: https://github.com/samvera-labs/bulkrax/blob/817e4bb826260c2b402f730e7696dd90027f0c0c/app/jobs/bulkrax/create_relationships_job.rb#L149
My suspicion is that it's erring on that line above. That's where the current user's ability is tested and where a `Hydra::AccessControl` would come into play in this situation. I'm now digging through logs to confirm this.

**Comment by bwatson78** [comment]
Also, I have been able to run both processes from rails console, and the associations occur. The only error that occurs is tied to the expectation of HydraRolesManagement being installed. 

I've also found that 500s occur whenever I attempt to edit FileSets.
