### ISSUE TITLE
Redirect OpenEmory "Contact Us" page to SCO "Meet the Scholarly Communications Office"

### ISSUE THREAD

**Issue by fpici** [emory-libraries/OpenEmory#20]

**Comment by fpici** [comment]
Lisa and Jody asked that we redirect the OpenEmory Contact Us page located here: https://open.library.emory.edu/feedback/ TO the SCO "Meet the Scholarly Communications Office" located here: http://sco.library.emory.edu/about/staff.html

**Comment by fpici** [comment]
Hi Zo. Any updates on this ticket? Many thanks!

**Comment by alexBLR** [comment]
Updated contact us page

**Comment by fpici** [comment]
Zo. The "Contact Us" at the top looks good BUT there are two other places for "Contact Us" located under the About OpenEmory  Menu Bar and at the bottom of the application that are both still going to the old Contact Form. See scrrenshots

**Comment by fpici** [comment]
See screenshots ... sorry :-(
![Screen Shot 2019-02-11 at 2.53.30 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216455f26b7191a37af117284f5c5f5ecc3c4a4356bcbbd671f3e57862804e0ee4806b0c7d973919faed824ee901ba21d8468ce7bfdf44d2f42f67b6d5db1063474f4dcbed5727a19141c95df242e84c51ad113565e27f2431.png)
![Screen Shot 2019-02-11 at 2.51.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216455f26b7191a37af1172a4f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ee4806b0c7d973919faed824ee901ba21d8468ce7bfdf44d2f42f67b6d5db1063474f4dcbed5727a19e41c95df242e84c51ad103667e27f2431.png)
