### ISSUE TITLE
Production: Generic form error when trying to submit a new work with all required fields populated

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#205]
I've now tried to upload 3 works into production. The initial upload works fine, but when I complete the required metadata and click Submit, I get a generic form validation error in yellow at the top of the form.

The first time I was able to Submit by saving a draft, and then resubmitting. I thought it was related to the CC license issue that Kyle reported in a Service Now ticket.
The next several tries, I received the same generic error whether or not I had entered a Creative Commons license.

You can see my incomplete submissions here:
https://open.library.emory.edu/profiles/eporter/

Also the first work I did submit is here (had to save as draft first, then submit)
https://open.library.emory.edu/publications/emory:w5x3f/

**Comment by eporter23** [comment]
Tricia Clayton (who has never logged into OpenEmory before) was able to successfully upload a new work: https://open.library.emory.edu/publications/emory:w5x70/

I continue to have the same "incomplete or missing" fields error on new submissions, whether or not they have a CCL assigned.
[https://app.zenhub.com/files/8471248/3a94c037-5418-43b7-a712-0e249f2bba55/download](https://app.zenhub.com/files/8471248/3a94c037-5418-43b7-a712-0e249f2bba55/download) 
[https://app.zenhub.com/files/8471248/ecc2b78b-48e5-418a-93fd-84a966dad98d/download](https://app.zenhub.com/files/8471248/ecc2b78b-48e5-418a-93fd-84a966dad98d/download)

**Comment by eporter23** [comment]
Kylie also experiences the same issue with not being able to Submit on a new work - can only save a draft.

**Comment by eporter23** [comment]
John Morgenstern (non-admin user) was able to upload successfully: https://open.library.emory.edu/publications/emory:w5xj7/

**Comment by alexBLR** [comment]
We have identified the error based on the logs.

I checked the fedora XACML, user permissions, and update functionality for OE.
