### ISSUE TITLE
BUG: Hyrax v4 Clean Install/Fedora6/ActiveFedora Returns 500 Error When Visiting FileSet#Edit

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/OpenEmory#208]
This error seems to be tied to Hyrax code. More details can be found here: https://github.com/samvera/hyrax/issues/6132

**Comment by bwatson78** [comment]
This is no longer occurring in production with my latest import: https://sandbox3.libraries.emory.edu/concern/parent/tq57nr00k/file_sets/05741r680

**Comment by eporter23** [comment]
This appears to be related to the difference in versioning in Hyrax/Fedora 4 vs Fedora 6
