### ISSUE TITLE
Requesting OpenEmory Admin Access for New SCO Spec. Sr.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/OpenEmory#21]
Requesting OpenEmory Admin Access for New SCO Spec. Sr.: NetID: KSHANN4. Name: Shannon, Kylie E.-- (kylie.shannon@emory.edu).  Many thanks in advance!

**Comment by fpici** [comment]
Hi Zo. Any updates on this ticket? Many thanks!

**Comment by alexBLR** [comment]
done.
