### ISSUE TITLE
Store authors affiliations in addition to the order of publication entry

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#210]
This ticket follows prior work identified in #200 and #169.

In addition to preserving the publication order of author entries on a work, we also want to store their affiliation. 
Additionally, the ability to separate first from last names will be useful in order to facet by last names instead of first names.

Below shows how the current OpenEmory data entry fields for authors is presented:
![Screen Shot 2023-08-03 at 1.41.59 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/5b54772c-9a5d-473e-8a7c-0bdbae786de4)

For future use cases, we want to be able to support:

- Bulk ingest (or migration) of existing OpenEmory works
- Direct Hyrax-based self deposit of works using the Create Work form

**Comment by abelemlih** [comment]
@eporter23 This ticket is ready for testing on sandbox

**Comment by eporter23** [comment]
Looks great @abelemlih ! I will consider some enhancements on this if time permits, but it is a fantastic addition.
