### ISSUE TITLE
Document system architecture/dependencies for LTDS support needs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#213]
As part of our project tasks and charter, we are charged with updating or creating technical system documentation. 

Recommendation:
Create a basic system architecture diagram for openemory
OR, document major components requiring support by Middleware and Software Engineering

Related documentation:
[Software Engineering Applications Inventory](https://emory.sharepoint.com/:x:/r/sites/EULLTDS/Shared%20Documents/Departments%20and%20Units/Technology%20Development%20and%20Operations/Inventories/Software%20Development%20Applications%20Inventory.xlsx?d=w826d1ab6fcb744a3b86012cd4ab24a3f&csf=1&web=1&e=ERRyTb)
[Ingest process map from 2017](https://emory.sharepoint.com/:b:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/02%20Project%20Archive/DLP%20-%20Discovery%20and%20Planning%20Phases/DLP%20Project/Discovery%20Phase%20-%20Current%20State%20Docs/Workflows%20and%20Process%20Maps/Current%20State%20Repository%20Ingest%20Process%20Maps/OpenEmoryIngestProcessMarch2017.pdf?csf=1&web=1&e=8ooNw2)

**Comment by tmiles2** [comment]
@rotated8 Is there an update on the diagram you discussed creating?

**Comment by rotated8** [comment]
It is in progress, but I haven't had enough time to finish it yet.
