### ISSUE TITLE
OpenEmory Statistics on the Page (Views and Downloads)

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/OpenEmory#22]
Original submission to LTDS on 2019-07-23

***Please route this request to LTDS***

Lisa Macklin and Sarah McKee have requested investigation of stats for the book "Ontological Terror: Blackness, Nihilism, and Emancipation" by Calvin Warren, which is housed in OpenEmory at https://pid.emory.edu/ark:/25593/s97s9 Here is more context around the request that Lisa provided via email:

"Professor Warren’s book in OpenEmory was funded as part of Emory’s Mellon grant supporting OA books by our faculty. . . .  If you look at the record . . ., you’ll notice that the number of downloads (3,439) is significantly higher than the number of views (539).  This is typically not the case with OpenEmory, where often the work is viewed more times than it is downloaded.  Do we have any additional information on these downloads either from the back end of OpenEmory or from Google Analytics that might help explain this anomaly?  It’s interesting that . . . on July 11th there were 3,292 and today (7/17) there are 3,439 downloads.  That’s 147 downloads in less than week.

After reviewing the issue LTDS determined:

OpenEmory stats issue - we believe bots or traffic coming from outside the site are adding to the totals. If you have a direct link to the PDF you can increase the download number without visiting the "view" page. The way the numbers on the page are setup seem to be simple page visitings without controlling for sessions. There seem to be legit users in the mix but the server logs only go back a few months. Development on the app to control sessions/cookies to help increase fidelity of the numbers would be better but would require priority, time and resources. I'm closing this ticket and making a note of this issue in the OpenEmory backlog.

**Comment by rotated8** [comment]
As noted, closing this for the record.
