### ISSUE TITLE
Test.open - Fedora Test OS upgrades: Permissions Denied 401 errors

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#223]
As part of the server OS upgrades project, I am testing testopen.library after the Fedora QA server was updated.

In several parts of the application I am running into what appears to be the same error when trying to view or edit a work. I have gotten this error in the following conditions:

1. Not logged in, attempting to view a work detail page
2. Logged in (as Admin user), attempting to edit a work record

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--347b5131fc613190960053c16a75570c0d2ccead/Work%20Record%20401%202023-10-23%20at%209.25.11%20AM.png)

**Additional Notes:** 

- I have been able to view an *embargoed* work detail page while not logged in:
https://testopen.library.emory.edu/publications/emory:rr2kt/
- I am also able to download files successfully from search results pages/listings

**Comment by jcrompton42** [comment]
fixed. The issue of embargoed works appearing is unrelated to the backend fedora it seems so I am going to create a new ticket for that.
