### ISSUE TITLE
Testopen.library Fedora Server upgrades: Error when uploading new document

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#224]
As part of the Fedora QA server OS upgrades, I am testing in the testopen.library environment.

When trying to create a new work and upload a file, I get the following error: "There was an error uploading your document to the repository."

Steps taken:

1. Login to Dashboard
2. Click on Upload New Document
3. Fill out the required form fields, selected Poster as the type
4. Uploaded a PNG image
5. Clicked Continue
6. Receive error message

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzlnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6c8e1cc22754252647c122a4515f333b8590148/Upload%20Error%202023-10-23%20at%209.37.37%20AM.png)

**Comment by jcrompton42** [comment]
I had the wrong filepath in the config for uploads. This is fixed now.
