### ISSUE TITLE
Testopen - Fedora QA testing: self deposits are created but not findable

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#227]
After SCO did testing the week of 10/26/23, Kylie noticed that while she was able to complete a manual deposit, she could not locate the record via search or browsing Recently Added after it was created.

I also replicated this issue. The following work I created exists, the files can be downloaded, but it does not appear to be indexed:
https://testopen.library.emory.edu/publications/emory:rr3d7/

Also, the PID url for this record doesn't resolve (though that may be an existing issue with the test environment)

**Comment by alexBLR** [comment]
@eporter23  Please test this once again. The issue should be fixed.

**Comment by eporter23** [comment]
@alexBLR thanks - I just uploaded 2 new works and can discover them via search and in Recently Added.
