### ISSUE TITLE
Pidman QA testing for testopen Dec 2023

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#228]
For the server OS upgrade testing for Pidman QA, I went through the process of uploading a new work and testing the pid. The domain and URL populated for the QA pid contains errors and when clicking on the Permanent URL in the newly created record, the URL doesn't resolve correctly.

Note: this bug was identified earlier in #164 but we decided not to spend time fixing it. 

Testing Steps:

1. Uploaded a new work in testopen.library
2. Copied the PID URL and opened in new tab
3. Get 404 error (because it tries to resolve to open.library instead of testopen.library)
4. Logged into pidmanqa
5. Checked the newly created PID entry (see screenshot below)
6. Changed the domain from open to testopen and saved (see screenshot below)
7. Checked the PID link again and got an error (see screenshot below)
8. Went back to pidmanqa and reformatted the extraneous URL parameters
9. Saved changes (see https://pidqas.library.emory.edu/admin/pid/pid/548859/change/#targets-tab)
10. Checked the PID link again and it resolves correctly. See this work: https://testopen.library.emory.edu/publications/emory:rr3x9/

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3de7fd8c08d886f6933b0f9f34fc9b5decb0e73/Screen%20Shot%202023-12-07%20at%2012.09.38%20PM.png" alt="Screen Shot 2023-12-07 at 12.09.38 PM.png" />

<img width="1638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmRBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--988aa2b4ef47c12015c1848d02b6f7dd5b34ec20/Screen%20Shot%202023-12-07%20at%2012.13.14%20PM.png" alt="Screen Shot 2023-12-07 at 12.13.14 PM.png" />

<img width="1914" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmhBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a702b68402a3ba3a726dab3a611016cfe3b7082e/Screen%20Shot%202023-12-07%20at%2012.13.50%20PM.png" alt="Screen Shot 2023-12-07 at 12.13.50 PM.png" />

**Comment by alexBLR** [comment]
@eporter23 thank you for testing. Looks like the pid gets generated correctly through rest_api. We just have an old problem with the path on the OE application side.

**Comment by eporter23** [comment]
@alexBLR sounds good, do you think there is anything else we need to look at here? If not I can close this.
