### ISSUE TITLE
Assess and document migration findings

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#38]
Summarize major findings about support for Fedora 6 in Samvera/Hyrax
- [x] Review the [Migration Pilot Work Notes](https://docs.google.com/document/d/1qnauwDdlkflJ_I7T8y8CJ6gNEU7jjQT0dZ6olTLoPdI/edit) and tickets in this epic
- [x] Create a [summary matrix of testing results](https://docs.google.com/spreadsheets/d/1-3oZk0F1iiSyTWwvr8WjjfNJn0bKoOnmJNQp9onpe28/edit?usp=sharing)
- [x] Develop an [executive summary for project closeout and the Hyrax Fedora 6 Working Group
](https://docs.google.com/document/d/1f6m2JyacHyvgSTtPzaUee5VfsXosaXAySPlKFUB7ykk/edit)
Identify a recommendation for how to proceed with OpenEmory data migration in Phase 2
- [x] Fedora 6 or Fedora 4
- [x] Migration utility or Bulkrax

**Comment by eporter23** [comment]
@bwatson78 @abelemlih please review and comment on the [Pros and Cons section](https://docs.google.com/document/d/1qnauwDdlkflJ_I7T8y8CJ6gNEU7jjQT0dZ6olTLoPdI/edit#heading=h.7iryekwnm77r) at the end of the working notes before we meet next.

**Comment by abelemlih** [comment]
@eporter23 I have reviewed the notes, and they cover all the important topics/issues we discussed.

**Comment by bwatson78** [comment]
@eporter23 I don't have anything to add/change to the documents.
