### ISSUE TITLE
Document any data remediations needed for a full migration

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#40]
Running work notes related to migration [are here](https://docs.google.com/document/d/1qnauwDdlkflJ_I7T8y8CJ6gNEU7jjQT0dZ6olTLoPdI/edit#heading=h.2jljo0ndu4ud).
Additional documentation may also be produced later.

This documentation will note remediations needed for

- Files
- Metadata
- Object structures
- Hyrax entities and configurations needed

[Draft document](https://docs.google.com/document/d/1h-8vJvu1qXRv4OLYgsCzSJwQpBrOdzCYYhfigjtg-g8/edit)

**Comment by eporter23** [comment]
CCL 4 licenses need https://

**Comment by abelemlih** [comment]
@eporter23 I have reviewed the notes, and they cover all the important topics/issues we discussed.
