### ISSUE TITLE
Deploy prod code to new test server

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#45]
- [x] Install Python3
- [x] Compile mod_wsgi for Python3
- [x] Set up Apache, combining configuration for OE prod with the Fedora, database, and other test details from the existing OE test config.
- [x] Ensure connection to libmysqldev1
- [x] Ensure connection to libfedqa
- [x] Clone the Python3 OE code to this server
- [x] Switch DNS to point to the new OE test server.

**Comment by jcrompton42** [comment]
Created incident INC04005472 and request REQ148362 for the database access. I copied the code from webprd002 over to webprd001 and installed python3 and recompiled mod_wsgi. Currently if I fake out the hosts file I get a 500 error but it's difficult to say if that is just the db or not.

**Comment by eporter23** [comment]
Note: testopen is now behind VPN.
