### ISSUE TITLE
Research Fedora 3 > 6 Migration tools

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#46]
Review the [Fedora documentation](https://wiki.lyrasis.org/display/FEDORA6x/Migrate+to+Fedora+6#MigratetoFedora6-TheFedora3%E2%86%926MigrationPath) for the migration utilities. Identify what access is needed to run the tooling, and document what work is needed to complete it.

- [x] Review Fedora 3 to 6 Migration docs to get a sense of what is needed for this type of migration
Fedora wiki: https://wiki.lyrasis.org/display/FEDORA6x/Migrate+to+Fedora+6#MigratetoFedora6-TheFedora3→6MigrationPath
Fedora 6 GitHub:  https://github.com/fcrepo-exts/migration-utils#pid-migration-selection
- [x] Write up additional tickets related to implementation steps for Sprint 2 and beyond
- [x] Identify any questions or blockers related to getting started on this work in the future

**Comment by eporter23** [comment]
Note, this documentation may be helpful for migrating a subset of pids: https://github.com/fcrepo-exts/migration-utils#pid-migration-selection

**Comment by kbowaterskelly** [comment]
Documentation reviewed. Looks relatively straightforward, with some caveats according to the individual circumstances we have, such as possibly needing to select an appropriate filesystem for the system or tune our allocation block size. We'll want to run the migration in such a way that it outputs appropriate logs and do a test run consisting of part of the data to see how that works before we lock the Fedora instance and run the full export/migration. Then we should run validation, see: https://github.com/fcrepo-exts/fcrepo-migration-validator

Blockers:
Infrastructure will need to be created before implementing this.
A test run should be undertaken and validated before completing the migration.

Questions:
1. How many datastreams are in our Fedora 3 instance? How large is it?
2. Do we use any of the following features? Do we need them? If so, what steps will need to be taken?
- Features that will not be migrated:
    Disseminators (disseminator datastreams will be migrated, but they will no longer function in Fedora 6)
    Redirect (R) and external (E) datastream content (URLs will be copied)
    Solr index
    Resource index
    XACML policies (objects with POLICY datastreams attached will be migrated, but they will no longer control access in Fedora 6)


I need to think about this before I create new tickets on how to break this up, but I should have that done in this sprint.

**Comment by eporter23** [comment]
Thanks @kbowaterskelly! One thing to note is we will only be migrating a representative subset of the Fedora 3 content and that's a task for me to determine which objects/how many. I'll be working on that in the next sprint.

**Comment by kbowaterskelly** [comment]
Ayoub and Collin should only need access to the filesystem that contains Fedora.

**Comment by tmiles2** [comment]
@kbowaterskelly Did you have a chance to create the new tickets?

**Comment by eporter23** [comment]
Another note for posterity, we will want to make use of these options. The PID file will contain the list of IDs we want to migrate. We should also set the extensions flag to true because in our Fedora 3 environment, files download without a mime type which will make them hard to work with later.

> -p, --pid-file=<pidFile>   PID file listing which Fedora 3 objects to migrate
  -x, --extensions           Add file extensions to migrated datastreams based
                               on mimetype recorded in FOXML
                               Default: false
