### ISSUE TITLE
Enable access to Fedora 3 for Brad and Ayoub

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#47]
Based on the work in #46, set up Brad and Ayoub with the appropriate access to Fedora 3.

**Comment by eporter23** [comment]
Standup discussion: this may depend on what we learn from #46 in terms of what kind of access is needed.

**Comment by kbowaterskelly** [comment]
Meeting to resolve this is scheduled for today.

**Comment by kbowaterskelly** [comment]
Fedora 3 can be accessed via the usual method of SSHing to the EC2 instance, and Brad and Ayoub do have access to this.
