### ISSUE TITLE
Plan AWS infrastructure for Fedora 6 work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#48]
Possible location - within AVreserves AWS environment

- Fedora 6
- Hyrax
- SOLR (possibly, depending on Valkyrie use)

**Comment by rotated8** [comment]
@kbowaterskelly and @jcrompton42 will review plan for implementation when everyone is back.

**Comment by kbowaterskelly** [comment]
Direct migration is recommended (non FOXML).
Relevant excerpt from documentation:

Prerequisites

    A host machine with filesystem access to both the Fedora 3 disk storage (or exported FOXML files) and the target OCFL disk storage.
    The target allocated disk space should be roughly the size of your Fedora 3 repository occupied disk space.

    OCFL repositories typically contain many small files, so the allocation block size of your filesystem can make a difference. We recommend using relatively small allocation block sizes if possible to avoid excess bloat in your migrated content.

    The migration to Fedora 6 will create ~4 files per datastream, with additional files for versions and what is required by OCFL. If you have a large Fedora 3 repository with many datastreams, you should consider using a filesystem which allows for large amounts of files such as XFS, ZFS, or Btrfs. Filesystems which rely on a fixed inode table, such as ext4, may run out of inodes for files and cause the migration to fail. If you anticipate this could be an issue, talk with you system administrator to find a solution which works for your repository.
    Java 11 installed on the host machine.
    Knowledge of the Fedora 3 filesystem layout (legacy or Akubra), if migrating directly from Fedora 3 data on disk.

Features that will not be migrated:

    Disseminators (disseminator datastreams will be migrated, but they will no longer function in Fedora 6)
    Redirect (R) and external (E) datastream content (URLs will be copied)
    Solr index
    Resource index
    XACML policies (objects with POLICY datastreams attached will be migrated, but they will no longer control access in Fedora 6)

**Comment by jcrompton42** [comment]
Things we need for which I am making tickets: 

In aws account 247

- Listener group 
- Application load balancer pointing to listener group that accepts connections on 443 and 80  
- Ec2 instance for webapp with latest amazon linux 2 ami that belongs in listener group and allows connections on ports 22 and 80 
- Ec2 instance for fedora with latest amazon linux 2 ami that allows connections on port 9193 

Create in Emory infrastructure
- Create dns fedora-test.library.emory.edu pointing to big ip VIP
- Route VIP to alb on was that points to listener group
