### ISSUE TITLE
Implement AWS infrastructure for Fedora 6 work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#49]

**Comment by kbowaterskelly** [comment]
Prerequisites

    A host machine with filesystem access to both the Fedora 3 disk storage (or exported FOXML files) and the target OCFL disk storage.
    The target allocated disk space should be roughly the size of your Fedora 3 repository occupied disk space.

    OCFL repositories typically contain many small files, so the allocation block size of your filesystem can make a difference. We recommend using relatively small allocation block sizes if possible to avoid excess bloat in your migrated content.

    The migration to Fedora 6 will create ~4 files per datastream, with additional files for versions and what is required by OCFL. If you have a large Fedora 3 repository with many datastreams, you should consider using a filesystem which allows for large amounts of files such as XFS, ZFS, or Btrfs. Filesystems which rely on a fixed inode table, such as ext4, may run out of inodes for files and cause the migration to fail. If you anticipate this could be an issue, talk with you system administrator to find a solution which works for your repository.
    Java 11 installed on the host machine.
    Knowledge of the Fedora 3 filesystem layout (legacy or Akubra), if migrating directly from Fedora 3 data on disk.

**Comment by kbowaterskelly** [comment]
Prerequisites

    A host machine with filesystem access to both the Fedora 3 disk storage (or exported FOXML files) and the target OCFL disk storage.
    The target allocated disk space should be roughly the size of your Fedora 3 repository occupied disk space.

    OCFL repositories typically contain many small files, so the allocation block size of your filesystem can make a difference. We recommend using relatively small allocation block sizes if possible to avoid excess bloat in your migrated content.

    The migration to Fedora 6 will create ~4 files per datastream, with additional files for versions and what is required by OCFL. If you have a large Fedora 3 repository with many datastreams, you should consider using a filesystem which allows for large amounts of files such as XFS, ZFS, or Btrfs. Filesystems which rely on a fixed inode table, such as ext4, may run out of inodes for files and cause the migration to fail. If you anticipate this could be an issue, talk with you system administrator to find a solution which works for your repository.
    Java 11 installed on the host machine.
    Knowledge of the Fedora 3 filesystem layout (legacy or Akubra), if migrating directly from Fedora 3 data on disk.

**Comment by kbowaterskelly** [comment]
I am not sure if you consider configuring the EC2 instance as part of AWS infrastructure. The above can be put into a new ticket if you like.
