### ISSUE TITLE
Application knowledge sharing (Valkyrie, Wings, OpenEmory, etc.)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#50]

**Comment by abelemlih** [comment]
### Valkyrie

As defined in this [repository](https://github.com/samvera/valkyrie):

> Valkyrie is a gem for enabling multiple backends for storage of files and metadata in Samvera.

Valkyrie will allows us to use one API to define resources and store/retrieve them from multiple backends. To switch between backends, we will use Valkyrie adapters. Valkyrie currently supports the following backends by default:

* Fedora
* Postgres
* Solr
* In-Memory

We will use the Fedora adapter to save files/metadata to Fedora 6.

#### Documentation

* Valkyrie Repository: https://github.com/samvera/valkyrie
* Valkyrie Wiki: https://github.com/samvera/valkyrie/wiki
* Valkyrie Tutorials: https://github.com/samvera/valkyrie/wiki/Dive-into-Valkyrie

#### Video Presentations

* What is Valkyrie (short intro): https://www.youtube.com/watch?v=nMmpIjuTk5c
* What is Valkyrie (long intro): https://www.youtube.com/watch?v=i0ljBYcbqFI

### Wings

Refer to the [following](https://groups.google.com/g/samvera-releases/c/9c9O-dIHmNI?pli=1) for a quick introduction to Wings:

> "Wings" is the name of the Hyrax-specific Valkyrie adapter we're experimentally supporting today. This adapter is designed to be used in-tandem with, or as a replacement for, the (soon to be) legacy ActiveFedora library. Wings achieves this by using ActiveFedora in its own internals, and providing mechanisms for translating between ActiveFedora's models and Valkyrie's resources. 

Wings is integrated into Hyrax: https://github.com/samvera/hyrax/blob/main/lib/wings.rb.

#### Video Presentations

* Using Valkyrie within Hyrax: https://www.youtube.com/watch?v=kBOt0SPctRw
* Hyrax/Wings update: https://www.youtube.com/watch?v=SBsConWkJAM


### Recommendations

Based on my research, I recommend the following in regards to the prototype we are building for this project:
* Wings is an intermediary between Valkyrie and ActiveFedora. Given that we want to avoid using/depending on ActiveFedora, I recommend we avoid building the prototype using Hyrax. Upgrading Hyrax to use Valkyrie exclusively, and removing the dependence on ActiveFedora and Wings, is still a work in progress.
* I recommend building a basic Rails app that uses Valkyrie and its Fedora adapter (Valkyrie supports Fedora 6). This prototype will enable us to develop internal expertise using Valkyrie to handle multiple backends. In our case, those backends could be Postgres, Solr, and Fedora.
* I recommend migrating a subset of OpenEmory data from Fedora 3 to Fedora 6, and using this prototype with the Valkyrie adapter, to demo writing/reading files and metadata from Fedora 6.

**Comment by abelemlih** [comment]
@rotated8 @bwatson78 @alexBLR I documented my findings in the comment above. Let me know if you have any questions/feedback. @rotated8 feel free to close this ticket if it contains all the documentation we need to start building the prototype.
