### ISSUE TITLE
Test current manual deposit functionality

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#52]
To address some open questions on the wireframes, when the test environment is operational again we need to test the existing 2012 functionality to confirm:

- [ ] If PDFs are currently required or other file types can be uploaded
- [ ] If a deposited work becomes public immediately if not embargoed
- [ ] What displays in the depositor's profile for a manually deposited work
- [ ] If a manually deposited work appears in the Review Queue
- [ ] If something like the Symplectic License is generated for the content model

**Comment by alexBLR** [comment]
@eporter23 please try again. I edit you to admin in fedora qa

**Comment by eporter23** [comment]
@alexBLR thanks, I still ran into the issue earlier this week but we can tackle it while we do more manual deposit testing.

**Comment by eporter23** [comment]
Closing this because we plan to address issues with test open as we encounter them during testing the work in the epic.
