### ISSUE TITLE
Finalize manual deposit wireframes

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#53]
This ticket follows the work done to create v.1 and v.2 of wireframes for the manual deposit process. Additional confirmations are pending from:

- [x] Testing/confirmation of existing 2012 functionality
- [x] Open questions regarding assent agreement language for SCO depositors
- [x] PDF requirement
- [x] Symplectic License file
- [x] LDAP/Emory data integration: selecting Emory authors who don't show up in the OE lookup

This will require followups with Software Engineering, Lisa and/or SCO.

Note: Additional wireframes or specifications may be identified regarding the static pages which are already editable by OpenEmory admins, but they are not a dependency for the manual deposit work.

[Application flow with links to wireframes](https://docs.google.com/drawings/d/1JuHpX2LWuWEkwMSGHtB5HVU8Z2QXmatWKvjN5UMYT5Q/edit)

**Comment by eporter23** [comment]
We got confirmation regarding checkbox item 2 above. Lisa confirmed the existing assent language for SCO depositors is okay. I also confirmed what the contents of the Symplectic License file is. For the PDF requirement, we need to test this further as part of manual deposit testing.

**Comment by eporter23** [comment]
@tmiles2 I'm moving this out of blocked because we got some information from Lisa, but there are still some questions that will require product testing to confirm. This will likely carry over into Sprint 4.

**Comment by tmiles2** [comment]
@eporter23 Sounds good. Thanks for the update.

**Comment by eporter23** [comment]
Wireframe updates to review with SCO after first pass of upload testing: JPEG vs JPG, rights research date field.

**Comment by eporter23** [comment]
When a deposit is uploaded by an Admin user, the following PREMIS is generated: ```<p:eventDetail>
Mediated Deposit with Assist Authorization or CC or PD by Emily Porter under OpenEmory v2.2.8-dev
</p:eventDetail>
<p:linkingAgentIdentifier>
<p:linkingAgentIdentifierType>netid</p:linkingAgentIdentifierType>
<p:linkingAgentIdentifierValue>eporter</p:linkingAgentIdentifierValue>
</p:linkingAgentIdentifier>
</p:event>```

**Comment by eporter23** [comment]
I'll confirm the Emory author lookup options with SCO in my next meeting on 6/22.

**Comment by eporter23** [comment]
After discussing with SCO, we agreed to keep the existing author lookup functionality as it is but will also add some guidance text to the form to help self depositors understand what to do if their Emory co-authors are not showing up. Wireframes will be updated.
