### ISSUE TITLE
Testopen: db related errors

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#59]
When doing some random navigating in the test environment 4/5/23 I encountered a few db/other errors:

login - authentication fails
![Screen Shot 2023-04-05 at 4.18.50 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/dcc94d7d-56cb-4d1a-b6ae-d69e8d71ec5f)

From the homepage, when clicking on any publication from the Most Viewed list, a 'DatabaseError' object has no attribute 'message' returns:
![Screen Shot 2023-04-05 at 4.16.07 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/4d76b820-3b60-4551-99db-52e0653e2a51)

(Note: doing a normal search and then accessing a record does function.)

Accessing the Browse options is showing varying behavior: 
Browse by Author seems to load very slowly and does not complete after several minutes.
Browse by Journal returns a list of matching works, but clicking on an individual record returns a similar Database Error noted above:

![Screen Shot 2023-04-05 at 4.25.51 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/5065a840-45b3-4212-bd45-7ee9c45a3105)

**Comment by tmiles2** [comment]
@jcrompton42 or @kbowaterskelly  can you take a look at this before our sprint planning meeting today?

**Comment by jcrompton42** [comment]
@tmiles2 I don't know how to fix this. It will have to wait for zo.

**Comment by jcrompton42** [comment]
I have resolved the oracle error so that publications can be viewed, however, the login error needs to be diagnosed by @alexBLR

**Comment by eporter23** [comment]
Looks good @jcrompton42 @alexBLR - thanks!
