### ISSUE TITLE
Migrate Prod Fedora 3 samples to 6

### ISSUE THREAD

**Issue by kbowaterskelly** [emory-libraries/OpenEmory#60]
Dependencies:

- [x] Review any relevant questions from #100 
- [x] Schedule a time for when this can occur because it will impact users
- [x] Clear out the old data first
- [x] Can we migrate into a container node instead of migrating to root? (e.g. fedora.../rest/root vs fedora.../rest/prod)
- [x] Use the pid list option to migrate the following: 
[PIDs to migrate](https://docs.google.com/spreadsheets/d/1qLzdhhOIXj9ebPAS58qWpWLUD8SMXGeIjR9re0qTfMQ/edit#gid=0)

**Comment by kbowaterskelly** [comment]
We'll run the migration in such a way that it outputs appropriate logs and do a test run consisting of part of the data to see how that works before we lock the Fedora instance and run the full export/migration. Then we should run validation, see: https://github.com/fcrepo-exts/fcrepo-migration-validator

We may be able to skip some portions of the full test harness if the QA migration goes well, but probably best not to.

This ticket is dependent on infrastructure being created, access being granted to those who will do the migration, and the test migration being completed successfully.

**Comment by eporter23** [comment]
We should make use of these options when running the utils. For the extensions flag, we should try setting that to true so that we have usable files (Fedora 3 downloads provide the files without a mime type currently)

> -p, --pid-file=<pidFile>   PID file listing which Fedora 3 objects to migrate
  -x, --extensions           Add file extensions to migrated datastreams based
                               on mimetype recorded in FOXML
                               Default: false

**Comment by eporter23** [comment]
While these tests are ~3 years old, might be of interest for estimating how long our test runs will take: https://wiki.lyrasis.org/display/FF/Fedora+3+to+6+Migration+Community+Updates

**Comment by jcrompton42** [comment]
Fedora doesn't natively support any alternate roots (/rest/prod or /rest/root) and while this may be possible it will take some work to implement. 

@rotated8 will consult stakeholders on the possibility of performing this migration tomorrow 5/26

**Comment by eporter23** [comment]
We think this run of 85 pids took several hours but don't have an exact end time since it ran overnight.
