### ISSUE TITLE
Start New Submission: Faculty Depositor View

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#64]
As a non-administrator logged into OpenEmory, they should see a form showing the following elements. See also the [wireframe for Faculty Self Depositor: Start New Submission](https://docs.google.com/drawings/d/1OHOT2beM0rwwoZZV_HKt1DG_tSFz0Eo8hZstZ2SbcKE/edit) 

- [x] **Revised language for the Assent to Deposit** section (provided by SCO/Lisa Macklin) - see below
- [x] **I accept these terms checkbox** - required, beneath the Assent to Deposit section
![Screen Shot 2023-04-12 at 10.04.07 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8d7f5019-4a48-4efa-ab36-77eb5fa5127f)
- [ ] **Type of Material** dropdown providing the ability to select from the additional content types
![Screen Shot 2023-04-12 at 10.03.42 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d59e40a2-b80e-495b-adc2-179d5fcfe591)

1. Article
2. Book
3. Book Chapter
4. Conference
5. Poster
6. Presentation
7. Report

- [x] **File Upload option** (heading revised from Upload PDF) - note, SCO is still trying to confirm if a PDF should be required by depositors or if the additional mime types are acceptable as deposits
![Screen Shot 2023-04-12 at 10.05.44 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7889fb8b-db42-4334-afbf-34bd78dc9a2c)

- [x] **Left blue sidebar heading changed to "Related Content"** to match what is shown elsewhere on the site

- [x] **Continue button** at end of form -- When the depositor clicks Continue, they should be routed to a form that matches the selected Type of material. See also additional tickets for this.   

### Revised Assent to Deposit Text
---
**Assent to Submit and Display Work***
My use of the OpenEmory self-deposit method confirms that I grant to Emory University the non-exclusive, perpetual license to preserve and reproduce the work, and to display, distribute and make the work publicly available without charge from the open access repository OpenEmory, or any successor initiative based at Emory, in any format.

I represent and warrant to Emory that:

- I have the right to submit the work to OpenEmory and to grant Emory the license above, or I have unrestricted permission from the copyright owner, such as a publisher, for the work to be distributed in an open access repository.
- Distribution from OpenEmory of the work does not infringe or violate any copyright or other rights of a publisher or other third party.
- If the work contains material for which I do not hold copyright, such as images, I have obtained all necessary rights for the work and the material to be distributed in OpenEmory.
- If the work was prepared jointly with other authors, I am granting the license above on their behalf as well as my own, and am authorized to do so.

I understand that I will have the option of specifying an embargo date to comply with publisher or funder policies, and Emory will delay making the work publicly available from OpenEmory until that date. I understand that I may request to have public access to my work restricted by removing public display to my work, and that Emory may remove my work from public display if Emory deems distribution is inappropriate, such as violating the rights of a third party.

I understand that this license is non-exclusive and does not prevent me from entering into similar arrangements with other parties or from exercising any rights that I may have in the work. However, I understand that I may need to inform subsequent publishers or others that I have granted this license to distribute my work in OpenEmory.

**Comment by alexBLR** [comment]
![Screen Shot 2023-04-19 at 2.19.31 PM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/1e30e40e-faa4-4040-bcb5-76de197522f0)

**Comment by eporter23** [comment]
@alexBLR Tiffany tested this today and she is receiving an error message when trying to upload a file. We tried different combinations of content types and permitted mime types but all returned the same generic error message and the upload did not complete. ![Screen Shot 2023-05-30 at 1.19.14 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/57758677-cea5-4ff8-b091-e039078241ce)

**Comment by eporter23** [comment]
@alexBLR Tiffany and I just tested and we are getting closer! She was able to upload a Presentation but got an error when trying to save entries to the metadata form. The work did get saved as a draft and show up in her dashboard which is good. 

![Screen Shot 2023-06-05 at 1.21.54 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/14399e8f-5bd8-462d-9ca2-a3161c0e9f53)

**Comment by eporter23** [comment]
@alexBLR here is the ID for the work Tiffany created in case you need it. Looks like it's been ingested but not indexed?   https://testopen.library.emory.edu/publications/emory:rr1vt

**Comment by eporter23** [comment]
Tested with Tiffany and this is working great now!
