### ISSUE TITLE
Start New Submission Form: Admin/SCO View

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#65]
As a user with administrator-level access to OpenEmory, they should see a submission form with the following elements. See also [wireframe for SCO depositors](https://docs.google.com/drawings/d/1AMyHu0ar-Yii2gMl4i2ShL2CtEm0DE1uuOmetXaFPkQ/edit).

- [x] Radio button selected for I am depositing work on behalf of a faculty member
- [x] Mediated Deposit language (no changes identified, but may need revisions later)
- [x] I accept these terms - required checkbox
- [x] Type of Material dropdown listing the additional content types

1. Article
2. Book
3. Book Chapter
4. Conference
5. Poster
6. Presentation
7. Report

- [x] File Upload option (relabeled from Upload PDF)
- [x] Continue button - routes the depositor to the appropriate form for the selected content type. See also additional tickets for the metadata form.

**Comment by alexBLR** [comment]
![Screen Shot 2023-04-19 at 2.17.31 PM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/c265c499-bab5-405e-a5c1-5005bea08da0)

**Comment by eporter23** [comment]
Form looks great! tested as an admin user. I'm not able to upload a file in testopen right now, so I will keep this open to make sure the mime type validation on accepted formats is working.

**Comment by eporter23** [comment]
File uploads are working, so closing this - looks good!
