### ISSUE TITLE
Faculty Depositor Profile: Dashboard and Documents views

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#67]
From testing in tickets #88 and #89, the following revisions are needed:

From the Dashboard or Documents view, a non-admin depositor should see the option to Upload New Document:

![Screen Shot 2023-06-06 at 10.24.12 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/efd49da0-a13d-43f9-8fc4-9a02053d82b7)

**Comment by alexBLR** [comment]
![Screen Shot 2023-06-13 at 8.52.56 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/1c75bb77-6365-41d7-8b6e-11825a1caf84)
