### ISSUE TITLE
Validate migrated QA fedora set

### ISSUE THREAD

**Issue by kbowaterskelly** [emory-libraries/OpenEmory#69]

**Comment by kbowaterskelly** [comment]
https://github.com/fcrepo-exts/fcrepo-migration-validator

The results of a migration can be validated against the source Fedora 3.x content using the fcrepo-migration-validator. This tool is capable of performing a number of validations and producing a report. Follow these steps to run the tool and produce a report:

    Download the latest version of fcrepo-migration-validator
    Follow the instructions in the README to configure and run the tool
    Review the report (available as HTML or TSV)

**Comment by eporter23** [comment]
Some initial findings: the mime type assignment for datastream files was applied and is working except for the RELS-EXT (ref/xml) which for me downloads with a .xmp extension. Not sure if this a Fedora bug, but could well be.

**Comment by jcrompton42** [comment]
Initial validation report run and present in libfedqa1:/home/fedora/csv/ but I believe Emily wants to meet about this so we'll talk about it when she gets back

**Comment by jcrompton42** [comment]
oh, it is on libfedqa1 the machine, and you are right, you don't have that, I'll zip the directory and share it

**Comment by eporter23** [comment]
When reviewing the validation options, we see that it outputs a CSV file for each PID. On a long migration, this seems problematic. It would also be useful if we could get a higher level summary of number of objects targeted to migrate and number of objects actually migrated. We are looking at whether or not this argument may help with this. ```-n, --check-num-objects   Enable validation comparing the number of objects
                              in the Fedora 3 and Fedora OCFL repositories.
                              This validation is always disabled if a PID File
                              is used.```

**Comment by jcrompton42** [comment]
currently the migrated objects are failing because metadata checks show that they were created at different times, I think because the sandbox fedora server is in UTC while libfedqa1 is in EST.
