### ISSUE TITLE
add a large Book file 81MB directly into fedora for a faculty deposit.

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/OpenEmory#7]
Pid: emory:s4h1r (81MB file too big to attach ... in Box here: https://emory.box.com/s/fw734azqx3b7a6k3g63655ra818ztkp7

**Comment by alexBLR** [comment]
Hi Zo. The file pdf is too big to push through the connector. We get timeout errors. We thought we could push a smaller file through the connector and then go directly into fedora and replace the file with the 81MB file. on the back end. What do you think?

**Comment by rosy1280** [comment]
[ ] Dummy file created
[ ] Dummy file replaced with file from box

**Comment by fpici** [comment]
@rosy1280 This ticket is tested and "Ready to Deploy." :-)

**Comment by fpici** [comment]
@rosy1280 Hmmmm? I cannot move this into "Ready to Deploy" and I cannot assign you to the ticket?
