### ISSUE TITLE
Valkyrie prototype: investigate new query method

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#73]
Placeholder ticket identified in sprint 3 planning

**Comment by eporter23** [comment]
ZenHub is acting flaky and I can't assign this to the epic but I will circle back.

**Comment by bwatson78** [comment]
This is not needed for the migrated data, but will live in a branch for future reference.

**Comment by rotated8** [comment]
I'll ask the Fedora Slack to confirm node membership limits as the exist in Fedora 4 are not an issue, and if that is the case, we can close this ticket as a non-issue. The Valkyrie gem will update to support our additional needs, if necessary (c.f. samvera/valkyrie#928 ).

**Comment by eporter23** [comment]
@rotated8 @bwatson78 not sure if this is directly related to this ticket, but I am wondering if we should consider whether or not to use Archival Groups (for how the OCFL objects are structured on disk). I guess it'd be helpful to look at our OCFL objects before even considering that.

**Comment by rotated8** [comment]
From the Fedora Slack: "having millions of objects at the root will still produce a huge RDF response, which can be problematic with some serializations". Sounds like pairtree is still recommended.
