### ISSUE TITLE
Valkyrie prototype: metadata parsing

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#75]
- Investigate how to parse metadata from binary files: can we read from them to populate RDF properties? 
- Investigate how to best assign PCDM relationships (de-scoped from this ticket)

**Comment by rotated8** [comment]
Here's the work breakdown I'd propose:

- [ ] Start by mapping a couple common metadata elements, and also a blob we can dump the rest of the metadata into.
This should allow us to create an edit interface where we can edit the mapped elements, and not lose anything by saving it in the "blob" for later. Valkyrie does not update an object but replaces it, so we need a place to hold on to unmapped metadata while we work on this or other features.
- [ ] Map some common DC metadata.
- [ ] Create a new controller function we can call to read an object's DC file and attempt to pull values for our mapped metadata.
- [ ] Map some ???MODS??? and update the ripper function to attempt to populate that metadata too.

After this we should probably decide where we want to go with this work and create new tickets to support that way forward.

cc @bwatson78 - I think this accurately reflects the direction we talked about today. Please let me know if I forgot something.

**Comment by rotated8** [comment]
For PCDM relationships, we can look at the predicates Hyrax uses in Fedora 4 and create those properties ourselves. Our Valkyrie repository would then need to understand how to validate the PCDM rules.

**Comment by eporter23** [comment]
For locally defined predicates, we use this base pattern:  http://metadata.emory.edu/vocab/cor-terms#fieldName 
Examples:  
http://metadata.emory.edu/vocab/cor-terms#authorNote
http://metadata.emory.edu/vocab/cor-terms#dataClassification

**Comment by eporter23** [comment]
For the MODS testing, we discussed extracting the following:
`<mods:genre authority="marcgt">Article</mods:genre>`
Curate field: `content_genres` 
Predicate: http://www.europeana.edu/schemas/edm/hasType
and
` <mods:genre authority="local">Final Publisher PDF</mods:genre>`
Curate field: `publisher_version`
Predicate: http://metadata.emory.edu/vocab/cor-terms#publicationStage
