### ISSUE TITLE
Valkyrie Prototype: PCDM basics

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/OpenEmory#82]
Linked to ticket #73.

One of our goals for this project is to attempt to connect a Hyrax repository to our Fedora 6 instance with Valkyrie. Hyrax makes assumptions about objects based on properties it stores on the nodes in Fedora. Some of those properties are related to the Portland Common Data Model, PCDM. In this ticket, we'll begin setting up and populating properties on our models to implement PCDM.

- [ ] TODO

For additional reference, [see mocked up Curate test objects](https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/33)

**Comment by tmiles2** [comment]
@rotated8 @eporter23 Here's the PCDM ticket.

**Comment by tmiles2** [comment]
@rotated8 during standup it sounded like the PCDM tickets are still pending. Ayoub will create and update the spike ticket with the work he's done so you can review it. Do you have an estimated timeframe to draft the PCDM tickets?

**Comment by abelemlih** [comment]
Refer to the following tickets:

- https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/94
- https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/96
- https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/97
