### ISSUE TITLE
Valkyrie Prototype: FileSet UI

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/OpenEmory#87]
Depends on #86

In order to show of our new FileSets, we need a UI.

- [x] Create and route a show page for FileSets. 
- [x] The FileSet show page should show off the metadata we get from Fedora similar to what we do for the Object show page.
- [x] It should also link back to the Object show page the file is associated with (for now, we can manipulate the FileSet ID to understand this relationship).
- [x] On the Object show page, add links for the supplemental files, the content file, and the provenanceMetadata file, as appropriate.

Minimally, the FileSet should support metadata for:
- [x] Original Filename
- [x] Content Type
- [x] File Size

**Comment by rotated8** [comment]
Question for @eporter23: Would you have a use for an index page for FileSets? It doesn't map to an existing feature in Hyrax that I'm aware of, but may have use for this prototype?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/fedora6-prototype/pull/13

**Comment by eporter23** [comment]
Looks great!
