### ISSUE TITLE
add redirects to the OpenEmory

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/OpenEmory#9]
Test and Production sites:         
 1.  /authors/oa-fund/ -> http://sco.library.emory.edu/open-access-publishing/oa-funding-support/index.html
2.   /publishing-your-data/ -> http://sco.library.emory.edu/research-data-management/publishing/

**Comment by rosy1280** [comment]
Link #1
[ ] The existing page within OE at https://open.library.emory.edu/authors/oa-fund/ would cease to exist.
[ ] The link in the navigation bar would direct users to http://sco.library.emory.edu/open-access-publishing/oa-funding-support/index.html

Link #2
[ ] The existing page within OE at https://open.library.emory.edu/publishing-your-data/ would cease to exist
[ ] The link in the navigation bar would direct users to http://sco.library.emory.edu/research-data-management/publishing/

**Comment by rosy1280** [comment]
Question for Fran: are there other places that these links exist within OpenEmory?

**Comment by fpici** [comment]
@rosy1280 Hi Rosalyn. I do not believe so :-)

**Comment by fpici** [comment]
@alexBLR Howdy Zo. 

Link 1 looks good in OE Test.

Link 2 redirect points to https://testopen.library.emory.edu/ and it should point here: http://sco.library.emory.edu/research-data-management/publishing/ 

Hope this helps!

**Comment by fpici** [comment]
@alexBLR Hi Zo.
Link 1 looks great OE Test.
Link 2 points here: https://testopen.library.emory.edu/   and it should be pointing here: http://sco.library.emory.edu/research-data-management/publishing/

Hope this helps, fran

**Comment by fpici** [comment]
@alexBLR Tested both re-directs and they look good :-) Thank you!

**Comment by fpici** [comment]
@rosy1280 This ticket is good to go into "Ready to Deploy." :-)

**Comment by fpici** [comment]
@rosy1280 Hmmmm? I cannot move this into "Ready to Deploy" and I cannot assign you to the ticket?
