### ISSUE TITLE
Spike: replicate an OpenEmory request to Fedora (curl, etc.) [placeholder]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#91]
To help diagnose our inability to modify data in Fedora 3 QA, we can try writing a direct request to Fedora outside of the OpenEmory application

**Comment by alexBLR** [comment]
Some good progress on investigating the issue with fedoraQA. Beth, Collin, I met and found out that when connecting to object as fedoraAdmin and trying to to update it, we see a successful update of the objects both in prod and QA.

When I connect to fedora QA as myself (azotov) and try to update the objects, it does so successfully in prod, but fedoraQA is throwing a 401 error.

Which means we some sort of authorization problem within fedora when a specific user tries to update the object, but not when fedoraAdmin updates the object.

We also noticed (might be related) a LDAP error when trying to save the object

**Comment by alexBLR** [comment]
New error after @jcrompton42 disabling basic auth in fedora

[04/May/2023 15:30:34] DEBUG:eulfedora.api::GET objects/emory:fjhxt/datastreams/descMetadata=>200: 0.015749 sec
[04/May/2023 15:30:35] DEBUG:eulfedora.api::PUT objects/emory:fjhxt/datastreams/descMetadata=>500: 0.159310 sec

200 for get request now.

From Fedora logs: (WebApplicationExceptionMapper) javax.ws.rs.WebApplicationException: org.fcrepo.server.errors.ObjectIntegrityException: Audit record must have responsibility.
