### ISSUE TITLE
Valkyrie Prototype: Add PCDM properties to works

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/OpenEmory#94]
This ticket is the first step towards adding the Portland Common Data Model (PCDM) to the prototype.

Tasks:

- [ ] Add PCDM properties to the `ValkyrieObject` model
- [ ] When user clicks "Populate Metadata From DC and MODS", add PCDM object properties to Fedora 6 metadata for that particular work
- [ ] Ensure "Populate Metadata From DC and MODS" is idempotent

**Comment by tmiles2** [comment]
Pending testing by @eporter23

**Comment by eporter23** [comment]
@abelemlih I see the addition of `rdf_type http://pcdm.org/models#Object`- looks great! That's all I should test for on this ticket, yes?

**Comment by abelemlih** [comment]
@eporter23 yes thanks!
