### ISSUE TITLE
Create and Test Solr Valkyrie Adapter

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/OpenEmory#95]
- [x] Research the proper adapter setup for Valkyrie to communicate with our Solr instance.
- [x] Create processing that can persist the current state of a Fedora6 object to a brand new (or existing) Solr instance by pressing a button on the prototype site's object show page.

**Comment by eporter23** [comment]
@bwatson78 I'd like to adjust the RDF predicates for FileSets before you index those - will try to get those to you ASAP.

**Comment by bwatson78** [comment]
@eporter23 or @rotated8 I'm building up the Solr Schema. Can you advise me how I should set this:
![Screen Shot 2023-05-16 at 9.07.56 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3de4a302-ee64-44ce-a097-5721a4abb7b5)

**Comment by rotated8** [comment]
@bwatson78 No idea! Sounds like we should set it to `false` and see if anything breaks.

**Comment by rotated8** [comment]
Separately, I'm curious if there's a quick and easy way to reindex everything.

**Comment by eporter23** [comment]
@bwatson78 I added some RDF predicate and SOLR notes here for FileSets: https://docs.google.com/spreadsheets/d/18UW0Fp-ekSRqIu01XeOnsMDu-6yAVUovgeeCiIUTu4A/edit#gid=514011838

**Comment by bwatson78** [comment]
The predicates have been updated in a separate PR (https://github.com/emory-libraries/fedora6-prototype/pull/14) and is now live.

**Comment by tmiles2** [comment]
Pending testing by @eporter23

**Comment by eporter23** [comment]
Looks great! I did want to note for posterity which we have already talked about, but there are some odd behaviors related to integers and URIs:
 ![Screen Shot 2023-05-23 at 4.35.21 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e6e14b80-0e78-4218-901e-ccd58d4db95f)

![Screen Shot 2023-05-23 at 4.35.08 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/90cc4492-9103-4063-8347-0ccf7eab893e)

**Comment by eporter23** [comment]
Another odd prefix ("id-") in the `contains_` fields: ![Screen Shot 2023-05-23 at 4.41.41 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/233335d0-9fb7-45d9-a6a5-691b351e9532)
