### ISSUE TITLE
Valkyrie Prototype: Add PCDM properties to filesets

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/OpenEmory#96]
Tasks:

- [ ] Add PCDM properties to the `ValkyrieFileSet` model
- [ ] When user clicks "Create FileSets from Attached Files", add PCDM object properties to Fedora 6 metadata for that particular fileset
- [ ] Ensure "Create FileSets from Attached Files" is idempotent
- [ ] Ensure PCDM `hasMember` is empty when "Remove FileSets Created from Attached Files" is clicked (at the work level)

**Comment by abelemlih** [comment]
@eporter23 for this ticket we will need to test the following:

When the button "Create FileSets from Attached Files" is clicked:
- Each fileset has the property `rdf_type` set to `http://pcdm.org/models#Object`
- Each fileset has the property `memberOf` set to the ID of the parent work
- The parent work has property `hasMember` set to the list of fileset IDs that belong to that work
- The button action is idempotent

When the button "Remove FileSets Created from Attached Files" is clicked:
- The parent work has property `hasMember` set to an empty array
- The button action is idempotent

**Comment by eporter23** [comment]
@abelemlih looks good! One thing I want to note is that in Hyrax-created objects, FileSets don't usually have memberOf (parent work) stored. I don't know if there is a reason for that, and it seems like a good thing to have, but wanted to mention it. Example from Fedora 4/Hyrax FileSet: http://fedora-cor-test.library.emory.edu/fcrepo/rest/prod/58/70/vt/4b/5870vt4bkn-cor
