### ISSUE TITLE
Valkyrie Prototype: Add PCDM properties to files

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/OpenEmory#97]
Tasks:

- [ ] When user clicks "Create FileSets from Attached Files", add PCDM file properties to Fedora 6 metadata for all relevant attached files
- [ ] Ensure "Create FileSets from Attached Files" is idempotent

**Comment by eporter23** [comment]
Looks great @abelemlih ! From my testing notes, I see:

Work:
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:bsdmn

Valkyrie created FileSet
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory%3Absdmn%3AAUDIT

Valkyrie created PCDM #File: 
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:bsdmn:AUDIT/original/fcr:metadata

The original migrated Fedora 6 binary file container (exists in addition to the new binary container above):
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:bsdmn/AUDIT/fcr:metadata
